before_install: cd api && export DATABASE_URL=postgres://postgres:mysecretpassword@localhost:5432/postgres
language: rust
rust:
  - stable
  - beta
  - nightly
jobs:
  allow_failures:
    - rust: nightly
  fast_finish: true
